### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by l0g4n1337** [lewisgibson/monopoly-go-bot#4] opened 2023-07-12 18:01 UTC
Hi, I tried your bot.
At the start.ps1 step, notepad opens for me.
However if I run python main.py and hit F2 it starts scanning, but nothing happens and the mouse doesn't move.

**Comment by MarcoReckless** [comment] 2023-07-12 18:04
Check #1, it has a fix, or you can just install the required packages again since the file was updated.

**Comment by SouzaRicardoG** [comment] 2023-07-12 23:04
> Hi, I tried your bot. At the start.ps1 step, notepad opens for me. However if I run python main.py and hit F2 it starts scanning, but nothing happens and the mouse doesn't move.

Hi @l0g4n1337, check if the problem is the siz of images...  
See my comment in the other issue...  
https://github.com/lewisgibson/monopoly-go-bot/issues/1#issuecomment-1633313457

**Comment by lewisgibson** [comment] 2023-07-25 19:57
Image detection issue. Closing due to lack of correspondence from the author.

**Closed by lewisgibson** 2023-07-25 19:57 UTC
